const quizData = [
    { question: "A premature infant born at 28 weeks gestation is experiencing severe respiratory distress. Medical imaging shows that the infant's alveoli are collapsing after each exhalation. The administration of which of the following substances would most directly address the root cause of this alveolar collapse?", options: [{ text: "A bronchodilator to expand the airway passages.", rationale: "While it opens airways, it does not address the surface tension inside the alveoli causing them to collapse.", isCorrect: false }, { text: "A corticosteroid to reduce inflammation in the lung tissue.", rationale: "Inflammation is not the primary cause of alveolar collapse in premature infants; lack of surfactant is.", isCorrect: false }, { text: "An artificial lipoprotein surfactant to reduce surface tension.", rationale: "Surfactant reduces the surface tension of water in the alveoli, preventing them from collapsing during exhalation, a common issue in premature lungs.", isCorrect: true }, { text: "Pure oxygen gas to increase the concentration gradient.", rationale: "Increasing oxygen does not prevent the physical collapse of the alveoli, though it might temporarily help with low blood oxygen.", isCorrect: false }], hint: "Think about the fluid lining the inside of the alveoli and what prevents the walls from sticking together when deflated." },
    { question: "A patient is admitted to the emergency room with carbon monoxide (CO) poisoning after using a gasoline generator indoors. Even though the patient is breathing rapidly and the air in the room has a normal partial pressure of oxygen (PO2), the patient experiences low oxygen partial pressure in the blood. Which of the following best explains this physiological response?", options: [{ text: "Carbon monoxide binds irreversibly to the alveoli walls, preventing oxygen diffusion.", rationale: "CO diffuses normally into the blood; it does not block the alveolar walls themselves.", isCorrect: false }, { text: "Carbon monoxide has a higher affinity for hemoglobin than oxygen, reducing the blood's oxygen-carrying capacity.", rationale: "CO binds to hemoglobin at the same site as oxygen but with much greater affinity, effectively locking oxygen out and preventing tissue delivery.", isCorrect: true }, { text: "Carbon monoxide paralyzes the diaphragm, resulting in decreased ventilation rates.", rationale: "The question states the patient is breathing rapidly, so ventilation mechanics are not the primary issue.", isCorrect: false }, { text: "Carbon monoxide reacts with water in the blood to form carbonic acid, causing fatal acidosis.", rationale: "Carbon dioxide forms carbonic acid in the blood, not carbon monoxide.", isCorrect: false }], hint: "Consider the primary transport molecule for oxygen in the blood and how carbon monoxide might interact with it." },
    { question: "A student attempts to invent a makeshift scuba system by breathing through a 3-meter-long garden hose while submerged just below the surface of a swimming pool. Even though the student has the muscular strength to expand their chest against the water pressure, they quickly begin to experience severe dizziness and a strong urge to breathe. What is the primary physiological reason for this?", options: [{ text: "The long hose significantly increases the anatomical dead space, resulting in the student simply moving the same exhaled, carbon dioxide-rich air back and forth into their lungs.", rationale: "Anatomical dead space is the volume of the airways where no gas exchange occurs (trachea, bronchi, etc.). Adding a 3-meter hose creates a massive dead space that likely exceeds the student's tidal volume, meaning fresh atmospheric air never actually reaches the alveoli.", isCorrect: true }, { text: "The partial pressure of oxygen from the atmosphere decreases proportionally with the length of the hose, leading to an inadequate diffusion gradient.", rationale: "The partial pressure of oxygen at the opening of the hose is the same as the surrounding atmosphere; the length of the tube does not alter the partial pressure of the incoming gas.", isCorrect: false }, { text: "The cold temperature of the water causes the smooth muscle in the bronchioles to severely constrict, preventing air from entering.", rationale: "While cold water can cause a mild shock response, the primary, unavoidable mechanical issue here is the volume of the tube replacing fresh air with exhaled air.", isCorrect: false }, { text: "The extended length of the hose requires the student to increase their breathing rate, leading to hyperventilation and a dangerous drop in blood carbon dioxide.", rationale: "The student is actually experiencing a dangerous build-up of CO2 (hypercapnia) and a lack of O2 because they are rebreathing their own exhaled air, not blowing off too much CO2.", isCorrect: false }], hint: "Consider what happens to the air you just exhaled when it gets trapped inside a very long tube, and what exactly you are pulling into your lungs during your next breath." },
    { question: "A group of high-altitude climbers camps at 5,000 meters above sea level. At this altitude, the atmospheric pressure is roughly half that at sea level, though the percentage of oxygen in the air remains at 21%. Why do the climbers experience shortness of breath and low oxygen partial pressure in the blood?", options: [{ text: "The decreased temperature at high altitudes limits the expansion of the lungs.", rationale: "While temperature is lower, air is warmed in the respiratory tract; this is not the primary cause of low blood oxygen.", isCorrect: false }, { text: "The partial pressure of oxygen in the alveoli is reduced, decreasing the diffusion gradient into the blood.", rationale: "Because total atmospheric pressure is lower, the partial pressure of oxygen is also lower, which reduces the driving force for oxygen to diffuse into the capillaries.", isCorrect: true }, { text: "The concentration of carbon dioxide in the atmosphere is significantly higher at high altitudes.", rationale: "The relative percentages of gases (O2, CO2, N2) remain roughly the same at high altitudes.", isCorrect: false }, { text: "Hemoglobin denatures due to the lower atmospheric pressure, preventing oxygen binding.", rationale: "Hemoglobin does not denature due to atmospheric pressure changes.", isCorrect: false }], hint: "Diffusion of gases relies on a concentration (or partial pressure) gradient between the alveoli and the blood." },
    { question: "A patient undergoes spirometry testing. The technician notes that the patient's forced expiratory volume (the amount of air they can forcefully exhale after a normal tidal exhalation) is significantly reduced, though their total lung capacity is normal. This suggests an impairment in which of the following?", options: [{ text: "Inspiratory reserve volume", rationale: "Inspiratory reserve volume relates to forced inhalation, not exhalation.", isCorrect: false }, { text: "Expiratory reserve volume", rationale: "Expiratory reserve volume is the extra volume of air that can be expired forcefully after a normal tidal expiration, which fits the technician's observation.", isCorrect: true }, { text: "Tidal volume", rationale: "Tidal volume is the volume of air inhaled and exhaled during normal, resting breathing.", isCorrect: false }, { text: "Residual volume", rationale: "Residual volume is the air left in the lungs after a maximum forced exhalation; it cannot be forcefully exhaled.", isCorrect: false }], hint: "Think about the specific term for the extra air you can push out of your lungs after you finish a normal breath out." },
    { question: "During intense physical exercise, muscle cells produce high levels of carbon dioxide. How does this increased CO2 production affect the oxygen transport function of hemoglobin in those specific tissues?", options: [{ text: "High CO2 increases blood pH, causing hemoglobin to bind oxygen more tightly.", rationale: "High CO2 decreases blood pH (makes it more acidic), it does not increase it.", isCorrect: false }, { text: "High CO2 decreases blood pH, reducing hemoglobin's affinity for oxygen and promoting its release.", rationale: "Increased CO2 forms carbonic acid, lowering pH. This acidic environment changes hemoglobin's shape, reducing its affinity for oxygen and ensuring oxygen is unloaded exactly where it is needed most.", isCorrect: true }, { text: "CO2 directly binds to the iron centers in hemoglobin, physically displacing the oxygen molecules.", rationale: "CO2 binds to the amino acids in the globin protein chains, not the iron centers (which are for oxygen).", isCorrect: false }, { text: "High CO2 causes hemoglobin to break down into its constituent amino acids, releasing all stored oxygen.", rationale: "Hemoglobin does not break down in response to CO2; it merely undergoes a conformational change.", isCorrect: false }], hint: "Consider how carbon dioxide interacts with water in the blood to affect pH, and how that pH change affects the shape of proteins like hemoglobin." },
    { question: "A swimmer takes rapid, deep breaths (hyperventilates) before diving underwater in an attempt to hold their breath longer. Why is this practice dangerous?", options: [{ text: "It drastically increases the oxygen in the blood, leading to oxygen toxicity.", rationale: "Hemoglobin is already near 100% saturated with oxygen during normal breathing; taking deeper breaths does not significantly increase blood oxygen levels.", isCorrect: false }, { text: "It removes too much carbon dioxide from the blood, delaying the natural urge to breathe.", rationale: "The urge to breathe is triggered by high carbon dioxide levels, not low oxygen. Hyperventilating removes so much CO2 that the swimmer might run out of oxygen and pass out before feeling the need to breathe.", isCorrect: true }, { text: "It tires out the chest muscles, making it too difficult to swim back to the surface.", rationale: "While it takes energy to breathe deeply, this is not the primary physiological danger of hyperventilating before a dive.", isCorrect: false }, { text: "It causes the lungs to over-expand and rupture under the water pressure.", rationale: "Taking deep breaths before a dive does not cause the lungs to rupture; pressure changes during ascent can, but that is a different issue.", isCorrect: false }], hint: "Remember that your brain monitors the amount of a specific waste gas in your blood, rather than oxygen, to tell you when it is time to take a breath." },
    { question: "A patient is diagnosed with emphysema, a condition characterized by the destruction of the alveolar walls, leading to large, irregular air sacs. What is the primary reason this anatomical change impairs gas exchange?", options: [{ text: "It decreases the total surface area available for diffusion between the alveoli and capillaries.", rationale: "Fewer, larger alveoli mean drastically less surface area compared to many tiny alveoli, which severely limits the rate of gas diffusion.", isCorrect: true }, { text: "It increases the thickness of the respiratory membrane, slowing down the diffusion of gases.", rationale: "Emphysema destroys the walls rather than thickening them.", isCorrect: false }, { text: "It prevents the production of mucus, drying out the respiratory tract.", rationale: "Emphysema primarily affects the alveolar walls.", isCorrect: false }, { text: "It paralyzes the cilia in the bronchioles, trapping stagnant air in the lungs.", rationale: "While smoking paralyzes cilia, the structural change of emphysema itself is the loss of alveolar surface area.", isCorrect: false }], hint: "Think about the mathematical relationship between the size/number of the air sacs and the efficiency of moving molecules across a membrane." },
    { question: "In the human body, the majority of carbon dioxide generated by cellular respiration is transported back to the lungs in which of the following forms?", options: [{ text: "Dissolved freely in the blood plasma.", rationale: "Only about 7-10% of carbon dioxide is transported dissolved directly in the plasma.", isCorrect: false }, { text: "Bound to the iron atom of the hemoglobin molecule.", rationale: "Oxygen binds to the iron atom; carbon dioxide binds to the globin chains.", isCorrect: false }, { text: "As bicarbonate ions in the blood plasma.", rationale: "Approximately 70% of carbon dioxide reacts with water (catalyzed by carbonic anhydrase) to form carbonic acid, which dissociates into bicarbonate ions and hydrogen ions.", isCorrect: true }, { text: "Bound to dissolved plasma proteins such as albumin.", rationale: "While some CO2 can bind to plasma proteins, it is a very small fraction compared to bicarbonate.", isCorrect: false }], hint: "Consider the chemical reaction catalyzed by the enzyme carbonic anhydrase inside red blood cells." },
    { question: "A medical researcher is testing a drug that completely inhibits the enzyme carbonic anhydrase. If this drug were administered to a patient, what would be the most immediate and dangerous consequence regarding gas transport?", options: [{ text: "Oxygen would be unable to bind to hemoglobin in the pulmonary capillaries.", rationale: "Carbonic anhydrase is not involved in oxygen binding to hemoglobin.", isCorrect: false }, { text: "Carbon dioxide would accumulate in the tissues because its conversion to a transportable ion form is blocked.", rationale: "Carbonic anhydrase rapidly converts CO2 to bicarbonate. Without it, CO2 conversion is too slow, leading to toxic CO2 buildup in tissues and altering blood pH.", isCorrect: true }, { text: "The blood would become rapidly alkaline due to an overproduction of bicarbonate ions.", rationale: "Inhibiting the enzyme would prevent the formation of bicarbonate, not cause an overproduction.", isCorrect: false }, { text: "The diaphragm would stop contracting due to a lack of ATP production in muscle cells.", rationale: "Carbonic anhydrase is involved in blood gas transport, not directly in cellular ATP production in the diaphragm.", isCorrect: false }], hint: "Recall the main chemical form in which CO2 travels through the bloodstream and the enzyme responsible for creating it." },
    { question: "During an asthma attack, a patient experiences wheezing and severe difficulty exhaling. This physiological response is primarily due to:", options: [{ text: "The collapse of the trachea due to weakening of the cartilaginous rings.", rationale: "Asthma affects the smaller airways, not the large cartilaginous trachea.", isCorrect: false }, { text: "A sudden decrease in atmospheric pressure compared to alveolar pressure.", rationale: "Atmospheric pressure does not suddenly change during an asthma attack.", isCorrect: false }, { text: "Spasms of the smooth muscle lining the bronchioles, coupled with excess mucus production.", rationale: "Asthma involves the constriction of smooth muscles in the bronchioles and inflammation/mucus, drastically reducing the airway diameter and making it difficult to push air out.", isCorrect: true }, { text: "Fluid leaking from the pulmonary capillaries into the alveolar spaces.", rationale: "This describes pulmonary edema or pneumonia, not an asthma attack.", isCorrect: false }], hint: "Think about the anatomy of the lower respiratory tract and which structures lack cartilage rings but have muscle that can contract." },
    { question: "A severe head injury causes damage to the brain stem, specifically the medulla oblongata. What immediate effect will this have on the patient's respiratory system?", options: [{ text: "The patient will lose the ability to consciously hold their breath.", rationale: "Conscious control of breathing is managed by the cerebral cortex, not the medulla.", isCorrect: false }, { text: "The patient will lose their involuntary, automatic breathing rhythm.", rationale: "The medulla oblongata contains the respiratory center that sends the automatic nerve impulses to the diaphragm and intercostal muscles to maintain resting breathing.", isCorrect: true }, { text: "Gas exchange in the alveoli will stop due to a lack of neurological stimulation to the capillaries.", rationale: "Gas exchange is a passive process of diffusion and does not require direct neurological stimulation.", isCorrect: false }, { text: "The vocal cords will permanently constrict, blocking the airway.", rationale: "The primary and most immediate life-threatening effect of medullary damage is the loss of the basic breathing drive.", isCorrect: false }], hint: "Consider which part of the brain is responsible for sending the rhythmic signals that cause you to breathe even when you are asleep or unconscious." },
    { question: "An individual with severe anemia has a lower-than-normal red blood cell count, but their lungs are functioning perfectly. If you were to measure the partial pressure of oxygen (PO2) in their arterial blood and their total blood oxygen content, what would you expect to find compared to a healthy individual?", options: [{ text: "Normal PO2, but lower total oxygen content.", rationale: "PO2 measures the oxygen dissolved in the plasma, which will be normal if the lungs work fine. However, total oxygen content is low because there is less hemoglobin available.", isCorrect: true }, { text: "Low PO2, and lower total oxygen content.", rationale: "The dissolved O2 in the plasma (PO2) will equilibrate with the alveolar air and remain normal.", isCorrect: false }, { text: "Normal PO2, and normal total oxygen content.", rationale: "Total oxygen content cannot be normal if there is a deficit in red blood cells.", isCorrect: false }, { text: "High PO2, but lower total oxygen content.", rationale: "The PO2 will not be higher than normal; it will just reach equilibrium with the alveoli.", isCorrect: false }], hint: "Remember that PO2 only measures the small amount of oxygen dissolved directly in the blood fluid, while most oxygen is carried by cells." },
    { question: "During normal quiet inhalation, what mechanical events must occur to draw air into the lungs?", options: [{ text: "The diaphragm relaxes and domes upward, decreasing thoracic volume.", rationale: "Relaxing the diaphragm causes exhalation, not inhalation.", isCorrect: false }, { text: "The external intercostal muscles contract, pulling the rib cage down and inward.", rationale: "The external intercostals pull the rib cage up and outward.", isCorrect: false }, { text: "The diaphragm contracts and flattens, increasing thoracic volume and decreasing alveolar pressure.", rationale: "Contraction of the diaphragm flattens it, expanding the chest cavity. This drops the pressure inside the lungs below atmospheric pressure, drawing air in.", isCorrect: true }, { text: "The internal intercostal muscles contract, actively expanding the chest wall.", rationale: "Internal intercostals are used for forced exhalation.", isCorrect: false }], hint: "Think about Boyle's Law: to get air to flow inward, the pressure inside the lungs must be lower than the air outside." },
    { question: "A student uses a spirometer to measure their lung volumes. They take the deepest breath possible and then exhale as much air as they possibly can. Which of the following terms describes this total volume of exhaled air?", options: [{ text: "Tidal volume", rationale: "Tidal volume is the amount of air inhaled or exhaled during a normal, resting breath.", isCorrect: false }, { text: "Vital capacity", rationale: "Vital capacity represents the maximum amount of air a person can actively move in and out of their lungs.", isCorrect: true }, { text: "Expiratory reserve volume", rationale: "Expiratory reserve volume is only the extra air exhaled *after* a normal tidal exhalation.", isCorrect: false }, { text: "Total lung capacity", rationale: "Total lung capacity includes the vital capacity plus the residual volume.", isCorrect: false }], hint: "Think about the term used for the absolute maximum, active 'living' capacity of the lungs." },
    { question: "The human respiratory tract has several defense mechanisms to protect against airborne pathogens and debris. Which of the following outlines the correct sequence of structures and defenses a dust particle would encounter as it travels from the nose toward the alveoli?", options: [{ text: "Nasal hairs → Cilia and mucus in trachea → Macrophages in alveoli", rationale: "Air is initially filtered by nasal hairs, then trapped by sticky mucus and swept upward by cilia, and finally engulfed by alveolar macrophages.", isCorrect: true }, { text: "Cilia in trachea → Nasal hairs → Lymph nodes in bronchioles", rationale: "Nasal hairs come before the trachea.", isCorrect: false }, { text: "Macrophages in nose → Epiglottis → Mucus in alveoli", rationale: "Macrophages are primarily in the alveoli, and healthy alveoli should not be filled with mucus.", isCorrect: false }, { text: "Mucus in pharynx → Pleural fluid → Cartilage rings", rationale: "Air does not enter the pleural fluid.", isCorrect: false }], hint: "Trace the path of air from the outside world inward, matching the physical barriers to their anatomical locations." },
    { question: "A patient with a history of long-term smoking presents with a chronic cough and frequent respiratory infections. A biopsy of the tracheal lining reveals a significant loss of ciliated epithelial cells. How does this specific cellular damage contribute to the patient's symptoms?", options: [{ text: "The loss of cilia reduces the surface area for gas exchange in the trachea.", rationale: "Gas exchange occurs in the alveoli, not the trachea.", isCorrect: false }, { text: "Without cilia, mucus and trapped pathogens cannot be effectively swept upward and away from the lungs.", rationale: "Cilia act as an 'escalator' to move mucus and trapped debris up to the pharynx to be swallowed or coughed out.", isCorrect: true }, { text: "The ciliated cells are responsible for secreting surfactant, leading to tracheal collapse.", rationale: "Surfactant is secreted by specialized cells in the alveoli.", isCorrect: false }, { text: "The loss of cilia disrupts the neural pathways that trigger the breathing reflex.", rationale: "Cilia are mechanical structures for clearing debris, not neural sensors.", isCorrect: false }], hint: "Think about the function of the tiny hair-like structures lining the major airways and what happens if debris is not removed from these passages." },
    { question: "During the process of exhalation in a resting human, which of the following accurately describes the mechanical and pressure changes occurring in the thoracic cavity?", options: [{ text: "Thoracic volume increases, causing the pressure inside the lungs (alveoli) to drop below atmospheric pressure.", rationale: "This describes the mechanics of inhalation.", isCorrect: false }, { text: "Thoracic volume decreases, causing the pressure inside the lungs (alveoli) to rise above atmospheric pressure.", rationale: "Exhalation at rest is passive. As the diaphragm and external intercostals relax, the chest cavity shrinks. The decreased volume causes the pressure inside the lungs to exceed atmospheric pressure, forcing air out.", isCorrect: true }, { text: "The diaphragm actively contracts, pushing upward to create a vacuum that pulls air out.", rationale: "The diaphragm relaxes to move upward during resting exhalation.", isCorrect: false }, { text: "Atmospheric pressure drops, naturally pulling the excess air out of the lungs.", rationale: "Atmospheric pressure remains relatively constant during a breathing cycle.", isCorrect: false }], hint: "Recall Boyle's law: as volume decreases, pressure increases. How does air flow between areas of high and low pressure?" },
    { question: "A patient with severe pneumonia has fluid accumulating inside their alveoli. This buildup of fluid severely impairs oxygen exchange. Which of the following best explains the mechanism of this impairment?", options: [{ text: "The fluid causes the hemoglobin molecules in the blood to rupture before they can bind oxygen.", rationale: "Pneumonia affects the alveolar spaces, not the structural integrity of hemoglobin.", isCorrect: false }, { text: "The fluid dramatically increases the diffusion distance between the alveolar air space and the pulmonary capillaries.", rationale: "Efficient gas exchange relies on a microscopically thin respiratory membrane. Fluid in the alveoli creates a thick barrier that oxygen must travel through, severely slowing the rate of diffusion.", isCorrect: true }, { text: "The fluid paralyzes the diaphragm, preventing the patient from inhaling fresh air.", rationale: "Pneumonia affects gas exchange at the tissue level, not the gross motor function of the diaphragm.", isCorrect: false }, { text: "The fluid chemically binds to the oxygen, converting it into carbon dioxide before it reaches the blood.", rationale: "Fluid does not chemically convert oxygen to carbon dioxide.", isCorrect: false }], hint: "Consider the physical distance gases must travel to get from the air inside the lungs into the bloodstream, and how a layer of liquid changes that distance." },
    { question: "Chemoreceptors that regulate breathing are found in the medulla oblongata, the carotid bodies, and the aortic bodies. The primary chemoreceptors in the medulla are most sensitive to changes in the concentration of which substance in the cerebrospinal fluid?", options: [{ text: "Dissolved Oxygen", rationale: "Peripheral chemoreceptors are sensitive to large drops in O2, but central chemoreceptors are not.", isCorrect: false }, { text: "Hydrogen ions", rationale: "Carbon dioxide diffuses into the cerebrospinal fluid, reacts with water to form carbonic acid, which dissociates into hydrogen ions. The primary chemoreceptors directly detect these H+ ions to regulate breathing.", isCorrect: true }, { text: "Bicarbonate ions", rationale: "Bicarbonate is a buffer, but it is the free hydrogen ions that trigger the chemoreceptors.", isCorrect: false }, { text: "Glucose", rationale: "The respiratory center uses pH levels, not glucose, to determine breathing rate.", isCorrect: false }], hint: "Carbon dioxide crosses the blood-brain barrier and reacts with the fluid inside. What is the direct chemical product of this reaction that alters the pH?" },
    { question: "Which of the following lists the correct pathway of an oxygen molecule as it travels from the atmosphere to the site of gas exchange in the lungs?", options: [{ text: "Pharynx → Larynx → Trachea → Bronchi → Bronchioles → Alveoli", rationale: "Air enters the nasal cavity/mouth, passes the pharynx (throat), larynx (voice box), down the trachea (windpipe), which splits into bronchi, smaller bronchioles, and finally the alveoli.", isCorrect: true }, { text: "Larynx → Pharynx → Trachea → Bronchioles → Bronchi → Alveoli", rationale: "The pharynx is located superior to (above) the larynx.", isCorrect: false }, { text: "Trachea → Pharynx → Larynx → Bronchi → Alveoli → Bronchioles", rationale: "This sequence is out of order.", isCorrect: false }, { text: "Pharynx → Trachea → Larynx → Bronchioles → Bronchi → Alveoli", rationale: "The larynx sits between the pharynx and trachea.", isCorrect: false }], hint: "Trace the anatomical route starting from the back of the throat, past the voice box, down the main windpipe, and branching into the smallest tubes." },
    { question: "A patient experiences paralysis of the epiglottis due to nerve damage. What is the most immediate danger to this patient's respiratory system?", options: [{ text: "An inability to forcefully exhale air, leading to a build-up of carbon dioxide.", rationale: "The epiglottis is not involved in the muscular force of exhalation.", isCorrect: false }, { text: "The aspiration of food or liquid into the trachea, potentially causing choking or pneumonia.", rationale: "The epiglottis acts as a trapdoor that closes over the glottis during swallowing. Without it, food and liquid can easily enter the airway.", isCorrect: true }, { text: "A failure to produce vocal sounds, rendering the patient mute.", rationale: "The immediate life-threatening danger is food entering the lungs, not muteness.", isCorrect: false }, { text: "A collapse of the upper airway during deep inhalation.", rationale: "The epiglottis does not provide structural support to the airway.", isCorrect: false }], hint: "Think about the intersection where the respiratory and digestive tracts cross, and the mechanism that ensures materials go down the correct tube." },
    { question: "Compare the processes of internal respiration and external respiration. Which of the following rows correctly identifies the direction of gas exchange in internal respiration?", options: [{ text: "Oxygen moves from alveoli to blood; Carbon dioxide moves from blood to alveoli.", rationale: "This describes external respiration.", isCorrect: false }, { text: "Oxygen moves from blood to tissue cells; Carbon dioxide moves from tissue cells to blood.", rationale: "Internal respiration refers to the exchange of gases between the systemic capillaries and the body's tissue cells.", isCorrect: true }, { text: "Oxygen moves from the atmosphere to the alveoli; Carbon dioxide moves from the alveoli to the atmosphere.", rationale: "This describes ventilation (breathing mechanics).", isCorrect: false }, { text: "Oxygen is utilized in the mitochondria; Carbon dioxide is produced in the Krebs cycle.", rationale: "This describes cellular respiration.", isCorrect: false }], hint: "Remember that 'external' happens at the boundary with the outside world (the lungs), while 'internal' happens deep within the body's systemic tissues." },
    { question: "If a person moves from sea level to a high-altitude city and stays there for several months, their body undergoes acclimatization. Which of the following physiological changes would you expect a blood test to reveal after this acclimatization period?", options: [{ text: "A decreased number of red blood cells to reduce the viscosity of the blood.", rationale: "The body needs more oxygen carriers, not fewer.", isCorrect: false }, { text: "An increased concentration of erythropoietin (EPO) leading to a higher red blood cell count.", rationale: "In response to chronic low oxygen levels at high altitude, the kidneys release EPO, which stimulates the bone marrow to produce more red blood cells.", isCorrect: true }, { text: "A mutation in the hemoglobin molecule giving it a lower affinity for oxygen.", rationale: "Acclimatization does not cause genetic mutations in hemoglobin.", isCorrect: false }, { text: "An increase in blood plasma volume while the red blood cell count remains static.", rationale: "Increasing plasma volume without increasing red blood cells would actually dilute the oxygen-carrying capacity.", isCorrect: false }], hint: "Think about how the kidneys respond to chronic low oxygen levels by signaling the bone marrow to compensate." },
    { question: "A healthy individual is running on a treadmill. As their exercise intensity increases, their muscle cells consume more oxygen and produce more carbon dioxide. Which of the following best describes the changes in the partial pressures of gases in the *venous* blood returning from these active muscles?", options: [{ text: "Decreased PO2 and increased PCO2", rationale: "Active muscles extract more oxygen from the blood (lowering venous PO2) and dump more carbon dioxide into the blood as a byproduct of cellular metabolism.", isCorrect: true }, { text: "Increased PO2 and decreased PCO2", rationale: "This would describe blood returning from the lungs (arterial blood).", isCorrect: false }, { text: "Decreased PO2 and decreased PCO2", rationale: "While PO2 decreases as tissues consume it, PCO2 must increase because it is actively being produced.", isCorrect: false }, { text: "Increased PO2 and increased PCO2", rationale: "Muscles consume oxygen, they do not produce it, so the venous PO2 drops.", isCorrect: false }], hint: "Consider what raw materials a working muscle pulls out of the blood stream to make energy, and what waste gas it throws back into the blood." }
];

let currentQuestionIndex = 0;
let score = 0;

// DOM Elements
const questionText = document.getElementById("question-text");
const optionsContainer = document.getElementById("options-container");
const feedbackContainer = document.getElementById("feedback-container");
const rationaleText = document.getElementById("rationale-text");
const hintText = document.getElementById("hint-text");
const nextBtn = document.getElementById("next-btn");
const quizContent = document.getElementById("quiz-content");
const resultsContainer = document.getElementById("results-container");
const scoreText = document.getElementById("score-text");
const currentQNum = document.getElementById("current-q-num");
const restartBtn = document.getElementById("restart-btn");

function loadQuestion() {
    feedbackContainer.classList.add("hidden");
    optionsContainer.innerHTML = "";
    
    const currentQuestion = quizData[currentQuestionIndex];
    questionText.innerText = `${currentQuestionIndex + 1}. ${currentQuestion.question}`;
    currentQNum.innerText = currentQuestionIndex + 1;

    currentQuestion.options.forEach((option, index) => {
        const button = document.createElement("button");
        button.innerText = option.text;
        button.classList.add("option-btn");
        button.addEventListener("click", () => selectOption(button, option));
        optionsContainer.appendChild(button);
    });
}

function selectOption(selectedBtn, optionData) {
    // Disable all buttons
    const buttons = optionsContainer.querySelectorAll(".option-btn");
    buttons.forEach(btn => btn.disabled = true);

    if (optionData.isCorrect) {
        selectedBtn.classList.add("correct");
        score++;
    } else {
        selectedBtn.classList.add("incorrect");
        // Highlight correct answer
        buttons.forEach((btn, index) => {
            if (quizData[currentQuestionIndex].options[index].isCorrect) {
                btn.classList.add("correct");
            }
        });
    }

    rationaleText.innerHTML = `<strong>Explanation:</strong> ${optionData.rationale}`;
    hintText.innerText = optionData.isCorrect ? "" : `Hint: ${quizData[currentQuestionIndex].hint}`;
    feedbackContainer.classList.remove("hidden");
}

nextBtn.addEventListener("click", () => {
    currentQuestionIndex++;
    if (currentQuestionIndex < quizData.length) {
        loadQuestion();
    } else {
        showResults();
    }
});

function showResults() {
    quizContent.classList.add("hidden");
    resultsContainer.classList.remove("hidden");
    scoreText.innerText = `You scored ${score} out of ${quizData.length}!`;
}

restartBtn.addEventListener("click", () => {
    currentQuestionIndex = 0;
    score = 0;
    quizContent.classList.remove("hidden");
    resultsContainer.classList.add("hidden");
    loadQuestion();
});

// Start the quiz
loadQuestion();
